// 'https://feed.lolesports.com/livestats/v1/window/110853020184706758?startingTime=2023-11-11T12:09:40.000Z';

export default {
	esportsGameId: '110853020184706758',
	esportsMatchId: '110853020184706753',
	gameMetadata: {
		patchVersion: '13.19.535.4316',
		blueTeamMetadata: {
			esportsTeamId: '99566404853058754',
			participantMetadata: [
				{
					participantId: 1,
					esportsPlayerId: '99566404810113891',
					summonerName: 'WBG TheShy',
					championId: 'Ornn',
					role: 'top',
				},
				{
					participantId: 2,
					esportsPlayerId: '102192147302633932',
					summonerName: 'WBG Weiwei',
					championId: 'Maokai',
					role: 'jungle',
				},
				{
					participantId: 3,
					esportsPlayerId: '98767975914916595',
					summonerName: 'WBG Xiaohu',
					championId: 'Azir',
					role: 'mid',
				},
				{
					participantId: 4,
					esportsPlayerId: '100205573983550103',
					summonerName: 'WBG Light',
					championId: 'Kalista',
					role: 'bottom',
				},
				{
					participantId: 5,
					esportsPlayerId: '99566404817393644',
					summonerName: 'WBG Crisp',
					championId: 'Renata',
					role: 'support',
				},
			],
		},
		redTeamMetadata: {
			esportsTeamId: '99566404853854212',
			participantMetadata: [
				{
					participantId: 6,
					esportsPlayerId: '103478281356330346',
					summonerName: 'BLG Bin',
					championId: 'KSante',
					role: 'top',
				},
				{
					participantId: 7,
					esportsPlayerId: '105516152837078491',
					summonerName: 'BLG XUN',
					championId: 'Sejuani',
					role: 'jungle',
				},
				{
					participantId: 8,
					esportsPlayerId: '99566404798393925',
					summonerName: 'BLG Yagao',
					championId: 'Jayce',
					role: 'mid',
				},
				{
					participantId: 9,
					esportsPlayerId: '106368692529261498',
					summonerName: 'BLG Elk',
					championId: 'Caitlyn',
					role: 'bottom',
				},
				{
					participantId: 10,
					esportsPlayerId: '110547957837987327',
					summonerName: 'BLG ON',
					championId: 'Lux',
					role: 'support',
				},
			],
		},
	},
	frames: [
		{
			rfc460Timestamp: '2023-11-11T12:09:40.226Z',
			gameState: 'in_game',
			blueTeam: {
				totalGold: 57691,
				inhibitors: 1,
				towers: 6,
				barons: 1,
				totalKills: 15,
				dragons: ['cloud', 'infernal', 'mountain', 'mountain'],
				participants: [
					{
						participantId: 1,
						totalGold: 9790,
						level: 15,
						kills: 0,
						deaths: 5,
						assists: 5,
						creepScore: 220,
						currentHealth: 0,
						maxHealth: 3981,
					},
					{
						participantId: 2,
						totalGold: 9839,
						level: 14,
						kills: 0,
						deaths: 3,
						assists: 9,
						creepScore: 155,
						currentHealth: 2727,
						maxHealth: 2727,
					},
					{
						participantId: 3,
						totalGold: 14959,
						level: 18,
						kills: 5,
						deaths: 2,
						assists: 3,
						creepScore: 313,
						currentHealth: 629,
						maxHealth: 2923,
					},
					{
						participantId: 4,
						totalGold: 15198,
						level: 15,
						kills: 9,
						deaths: 2,
						assists: 3,
						creepScore: 288,
						currentHealth: 0,
						maxHealth: 2112,
					},
					{
						participantId: 5,
						totalGold: 7905,
						level: 14,
						kills: 1,
						deaths: 1,
						assists: 10,
						creepScore: 36,
						currentHealth: 1197,
						maxHealth: 2331,
					},
				],
			},
			redTeam: {
				totalGold: 56893,
				inhibitors: 0,
				towers: 3,
				barons: 1,
				totalKills: 13,
				dragons: ['mountain'],
				participants: [
					{
						participantId: 6,
						totalGold: 10845,
						level: 16,
						kills: 2,
						deaths: 4,
						assists: 5,
						creepScore: 227,
						currentHealth: 0,
						maxHealth: 2976,
					},
					{
						participantId: 7,
						totalGold: 9863,
						level: 14,
						kills: 0,
						deaths: 3,
						assists: 7,
						creepScore: 159,
						currentHealth: 3977,
						maxHealth: 4045,
					},
					{
						participantId: 8,
						totalGold: 13440,
						level: 16,
						kills: 3,
						deaths: 2,
						assists: 3,
						creepScore: 283,
						currentHealth: 0,
						maxHealth: 2167,
					},
					{
						participantId: 9,
						totalGold: 13513,
						level: 15,
						kills: 5,
						deaths: 2,
						assists: 4,
						creepScore: 274,
						currentHealth: 490,
						maxHealth: 2084,
					},
					{
						participantId: 10,
						totalGold: 9232,
						level: 13,
						kills: 3,
						deaths: 4,
						assists: 3,
						creepScore: 34,
						currentHealth: 771,
						maxHealth: 1969,
					},
				],
			},
		},
		{
			rfc460Timestamp: '2023-11-11T12:09:40.823Z',
			gameState: 'in_game',
			blueTeam: {
				totalGold: 57691,
				inhibitors: 1,
				towers: 6,
				barons: 1,
				totalKills: 15,
				dragons: ['cloud', 'infernal', 'mountain', 'mountain'],
				participants: [
					{
						participantId: 1,
						totalGold: 9790,
						level: 15,
						kills: 0,
						deaths: 5,
						assists: 5,
						creepScore: 220,
						currentHealth: 0,
						maxHealth: 3981,
					},
					{
						participantId: 2,
						totalGold: 9839,
						level: 14,
						kills: 0,
						deaths: 3,
						assists: 9,
						creepScore: 155,
						currentHealth: 2727,
						maxHealth: 2727,
					},
					{
						participantId: 3,
						totalGold: 14959,
						level: 18,
						kills: 5,
						deaths: 2,
						assists: 3,
						creepScore: 313,
						currentHealth: 629,
						maxHealth: 2923,
					},
					{
						participantId: 4,
						totalGold: 15198,
						level: 15,
						kills: 9,
						deaths: 2,
						assists: 3,
						creepScore: 288,
						currentHealth: 0,
						maxHealth: 2112,
					},
					{
						participantId: 5,
						totalGold: 7905,
						level: 14,
						kills: 1,
						deaths: 1,
						assists: 10,
						creepScore: 36,
						currentHealth: 1197,
						maxHealth: 2331,
					},
				],
			},
			redTeam: {
				totalGold: 56893,
				inhibitors: 0,
				towers: 3,
				barons: 1,
				totalKills: 13,
				dragons: ['mountain'],
				participants: [
					{
						participantId: 6,
						totalGold: 10845,
						level: 16,
						kills: 2,
						deaths: 4,
						assists: 5,
						creepScore: 227,
						currentHealth: 0,
						maxHealth: 2976,
					},
					{
						participantId: 7,
						totalGold: 9863,
						level: 14,
						kills: 0,
						deaths: 3,
						assists: 7,
						creepScore: 159,
						currentHealth: 3977,
						maxHealth: 4045,
					},
					{
						participantId: 8,
						totalGold: 13440,
						level: 16,
						kills: 3,
						deaths: 2,
						assists: 3,
						creepScore: 283,
						currentHealth: 0,
						maxHealth: 2167,
					},
					{
						participantId: 9,
						totalGold: 13513,
						level: 15,
						kills: 5,
						deaths: 2,
						assists: 4,
						creepScore: 274,
						currentHealth: 490,
						maxHealth: 2084,
					},
					{
						participantId: 10,
						totalGold: 9232,
						level: 13,
						kills: 3,
						deaths: 4,
						assists: 3,
						creepScore: 34,
						currentHealth: 771,
						maxHealth: 1969,
					},
				],
			},
		},
		{
			rfc460Timestamp: '2023-11-11T12:09:41.224Z',
			gameState: 'in_game',
			blueTeam: {
				totalGold: 57701,
				inhibitors: 1,
				towers: 6,
				barons: 1,
				totalKills: 15,
				dragons: ['cloud', 'infernal', 'mountain', 'mountain'],
				participants: [
					{
						participantId: 1,
						totalGold: 9792,
						level: 15,
						kills: 0,
						deaths: 5,
						assists: 5,
						creepScore: 220,
						currentHealth: 0,
						maxHealth: 3981,
					},
					{
						participantId: 2,
						totalGold: 9841,
						level: 14,
						kills: 0,
						deaths: 3,
						assists: 9,
						creepScore: 155,
						currentHealth: 2727,
						maxHealth: 2727,
					},
					{
						participantId: 3,
						totalGold: 14961,
						level: 18,
						kills: 5,
						deaths: 2,
						assists: 3,
						creepScore: 313,
						currentHealth: 633,
						maxHealth: 2923,
					},
					{
						participantId: 4,
						totalGold: 15200,
						level: 15,
						kills: 9,
						deaths: 2,
						assists: 3,
						creepScore: 288,
						currentHealth: 0,
						maxHealth: 2112,
					},
					{
						participantId: 5,
						totalGold: 7907,
						level: 14,
						kills: 1,
						deaths: 1,
						assists: 10,
						creepScore: 36,
						currentHealth: 823,
						maxHealth: 2331,
					},
				],
			},
			redTeam: {
				totalGold: 56903,
				inhibitors: 0,
				towers: 3,
				barons: 1,
				totalKills: 13,
				dragons: ['mountain'],
				participants: [
					{
						participantId: 6,
						totalGold: 10847,
						level: 16,
						kills: 2,
						deaths: 4,
						assists: 5,
						creepScore: 227,
						currentHealth: 0,
						maxHealth: 2976,
					},
					{
						participantId: 7,
						totalGold: 9865,
						level: 14,
						kills: 0,
						deaths: 3,
						assists: 7,
						creepScore: 159,
						currentHealth: 3956,
						maxHealth: 4045,
					},
					{
						participantId: 8,
						totalGold: 13442,
						level: 16,
						kills: 3,
						deaths: 2,
						assists: 3,
						creepScore: 283,
						currentHealth: 0,
						maxHealth: 2167,
					},
					{
						participantId: 9,
						totalGold: 13515,
						level: 15,
						kills: 5,
						deaths: 2,
						assists: 4,
						creepScore: 274,
						currentHealth: 492,
						maxHealth: 2084,
					},
					{
						participantId: 10,
						totalGold: 9234,
						level: 13,
						kills: 3,
						deaths: 4,
						assists: 3,
						creepScore: 34,
						currentHealth: 773,
						maxHealth: 1969,
					},
				],
			},
		},
		{
			rfc460Timestamp: '2023-11-11T12:09:42.223Z',
			gameState: 'in_game',
			blueTeam: {
				totalGold: 57713,
				inhibitors: 1,
				towers: 6,
				barons: 1,
				totalKills: 15,
				dragons: ['cloud', 'infernal', 'mountain', 'mountain'],
				participants: [
					{
						participantId: 1,
						totalGold: 9795,
						level: 15,
						kills: 0,
						deaths: 5,
						assists: 5,
						creepScore: 220,
						currentHealth: 0,
						maxHealth: 3981,
					},
					{
						participantId: 2,
						totalGold: 9843,
						level: 14,
						kills: 0,
						deaths: 3,
						assists: 9,
						creepScore: 155,
						currentHealth: 2727,
						maxHealth: 2727,
					},
					{
						participantId: 3,
						totalGold: 14963,
						level: 18,
						kills: 5,
						deaths: 2,
						assists: 3,
						creepScore: 313,
						currentHealth: 637,
						maxHealth: 2923,
					},
					{
						participantId: 4,
						totalGold: 15202,
						level: 15,
						kills: 9,
						deaths: 2,
						assists: 3,
						creepScore: 288,
						currentHealth: 0,
						maxHealth: 2112,
					},
					{
						participantId: 5,
						totalGold: 7910,
						level: 14,
						kills: 1,
						deaths: 1,
						assists: 10,
						creepScore: 36,
						currentHealth: 833,
						maxHealth: 2331,
					},
				],
			},
			redTeam: {
				totalGold: 56915,
				inhibitors: 0,
				towers: 3,
				barons: 1,
				totalKills: 13,
				dragons: ['mountain'],
				participants: [
					{
						participantId: 6,
						totalGold: 10849,
						level: 16,
						kills: 2,
						deaths: 4,
						assists: 5,
						creepScore: 227,
						currentHealth: 0,
						maxHealth: 2976,
					},
					{
						participantId: 7,
						totalGold: 9867,
						level: 14,
						kills: 0,
						deaths: 3,
						assists: 7,
						creepScore: 159,
						currentHealth: 3960,
						maxHealth: 4045,
					},
					{
						participantId: 8,
						totalGold: 13445,
						level: 16,
						kills: 3,
						deaths: 2,
						assists: 3,
						creepScore: 283,
						currentHealth: 0,
						maxHealth: 2167,
					},
					{
						participantId: 9,
						totalGold: 13517,
						level: 15,
						kills: 5,
						deaths: 2,
						assists: 4,
						creepScore: 274,
						currentHealth: 494,
						maxHealth: 2084,
					},
					{
						participantId: 10,
						totalGold: 9237,
						level: 13,
						kills: 3,
						deaths: 4,
						assists: 3,
						creepScore: 34,
						currentHealth: 785,
						maxHealth: 1969,
					},
				],
			},
		},
		{
			rfc460Timestamp: '2023-11-11T12:09:42.323Z',
			gameState: 'in_game',
			blueTeam: {
				totalGold: 57713,
				inhibitors: 1,
				towers: 6,
				barons: 1,
				totalKills: 15,
				dragons: ['cloud', 'infernal', 'mountain', 'mountain'],
				participants: [
					{
						participantId: 1,
						totalGold: 9795,
						level: 15,
						kills: 0,
						deaths: 5,
						assists: 5,
						creepScore: 220,
						currentHealth: 0,
						maxHealth: 3981,
					},
					{
						participantId: 2,
						totalGold: 9843,
						level: 14,
						kills: 0,
						deaths: 3,
						assists: 9,
						creepScore: 155,
						currentHealth: 2727,
						maxHealth: 2727,
					},
					{
						participantId: 3,
						totalGold: 14963,
						level: 18,
						kills: 5,
						deaths: 2,
						assists: 3,
						creepScore: 313,
						currentHealth: 637,
						maxHealth: 2923,
					},
					{
						participantId: 4,
						totalGold: 15202,
						level: 15,
						kills: 9,
						deaths: 2,
						assists: 3,
						creepScore: 288,
						currentHealth: 0,
						maxHealth: 2112,
					},
					{
						participantId: 5,
						totalGold: 7910,
						level: 14,
						kills: 1,
						deaths: 1,
						assists: 10,
						creepScore: 36,
						currentHealth: 833,
						maxHealth: 2331,
					},
				],
			},
			redTeam: {
				totalGold: 56915,
				inhibitors: 0,
				towers: 3,
				barons: 1,
				totalKills: 13,
				dragons: ['mountain'],
				participants: [
					{
						participantId: 6,
						totalGold: 10849,
						level: 16,
						kills: 2,
						deaths: 4,
						assists: 5,
						creepScore: 227,
						currentHealth: 0,
						maxHealth: 2976,
					},
					{
						participantId: 7,
						totalGold: 9867,
						level: 14,
						kills: 0,
						deaths: 3,
						assists: 7,
						creepScore: 159,
						currentHealth: 3960,
						maxHealth: 4045,
					},
					{
						participantId: 8,
						totalGold: 13445,
						level: 16,
						kills: 3,
						deaths: 2,
						assists: 3,
						creepScore: 283,
						currentHealth: 0,
						maxHealth: 2167,
					},
					{
						participantId: 9,
						totalGold: 13517,
						level: 15,
						kills: 5,
						deaths: 2,
						assists: 4,
						creepScore: 274,
						currentHealth: 494,
						maxHealth: 2084,
					},
					{
						participantId: 10,
						totalGold: 9237,
						level: 13,
						kills: 3,
						deaths: 4,
						assists: 3,
						creepScore: 34,
						currentHealth: 785,
						maxHealth: 1969,
					},
				],
			},
		},
		{
			rfc460Timestamp: '2023-11-11T12:09:42.424Z',
			gameState: 'in_game',
			blueTeam: {
				totalGold: 57713,
				inhibitors: 1,
				towers: 6,
				barons: 1,
				totalKills: 15,
				dragons: ['cloud', 'infernal', 'mountain', 'mountain'],
				participants: [
					{
						participantId: 1,
						totalGold: 9795,
						level: 15,
						kills: 0,
						deaths: 5,
						assists: 5,
						creepScore: 220,
						currentHealth: 0,
						maxHealth: 3981,
					},
					{
						participantId: 2,
						totalGold: 9843,
						level: 14,
						kills: 0,
						deaths: 3,
						assists: 9,
						creepScore: 155,
						currentHealth: 2727,
						maxHealth: 2727,
					},
					{
						participantId: 3,
						totalGold: 14963,
						level: 18,
						kills: 5,
						deaths: 2,
						assists: 3,
						creepScore: 313,
						currentHealth: 637,
						maxHealth: 2923,
					},
					{
						participantId: 4,
						totalGold: 15202,
						level: 15,
						kills: 9,
						deaths: 2,
						assists: 3,
						creepScore: 288,
						currentHealth: 0,
						maxHealth: 2112,
					},
					{
						participantId: 5,
						totalGold: 7910,
						level: 14,
						kills: 1,
						deaths: 1,
						assists: 10,
						creepScore: 36,
						currentHealth: 833,
						maxHealth: 2331,
					},
				],
			},
			redTeam: {
				totalGold: 56915,
				inhibitors: 0,
				towers: 3,
				barons: 1,
				totalKills: 13,
				dragons: ['mountain'],
				participants: [
					{
						participantId: 6,
						totalGold: 10849,
						level: 16,
						kills: 2,
						deaths: 4,
						assists: 5,
						creepScore: 227,
						currentHealth: 0,
						maxHealth: 2976,
					},
					{
						participantId: 7,
						totalGold: 9867,
						level: 14,
						kills: 0,
						deaths: 3,
						assists: 7,
						creepScore: 159,
						currentHealth: 3960,
						maxHealth: 4045,
					},
					{
						participantId: 8,
						totalGold: 13445,
						level: 16,
						kills: 3,
						deaths: 2,
						assists: 3,
						creepScore: 283,
						currentHealth: 0,
						maxHealth: 2167,
					},
					{
						participantId: 9,
						totalGold: 13517,
						level: 15,
						kills: 5,
						deaths: 2,
						assists: 4,
						creepScore: 274,
						currentHealth: 494,
						maxHealth: 2084,
					},
					{
						participantId: 10,
						totalGold: 9237,
						level: 13,
						kills: 3,
						deaths: 4,
						assists: 3,
						creepScore: 34,
						currentHealth: 785,
						maxHealth: 1969,
					},
				],
			},
		},
		{
			rfc460Timestamp: '2023-11-11T12:09:43.198Z',
			gameState: 'in_game',
			blueTeam: {
				totalGold: 57713,
				inhibitors: 1,
				towers: 6,
				barons: 1,
				totalKills: 15,
				dragons: ['cloud', 'infernal', 'mountain', 'mountain'],
				participants: [
					{
						participantId: 1,
						totalGold: 9795,
						level: 15,
						kills: 0,
						deaths: 5,
						assists: 5,
						creepScore: 220,
						currentHealth: 0,
						maxHealth: 3981,
					},
					{
						participantId: 2,
						totalGold: 9843,
						level: 14,
						kills: 0,
						deaths: 3,
						assists: 9,
						creepScore: 155,
						currentHealth: 2727,
						maxHealth: 2727,
					},
					{
						participantId: 3,
						totalGold: 14963,
						level: 18,
						kills: 5,
						deaths: 2,
						assists: 3,
						creepScore: 313,
						currentHealth: 637,
						maxHealth: 2923,
					},
					{
						participantId: 4,
						totalGold: 15202,
						level: 15,
						kills: 9,
						deaths: 2,
						assists: 3,
						creepScore: 288,
						currentHealth: 0,
						maxHealth: 2112,
					},
					{
						participantId: 5,
						totalGold: 7910,
						level: 14,
						kills: 1,
						deaths: 1,
						assists: 10,
						creepScore: 36,
						currentHealth: 833,
						maxHealth: 2331,
					},
				],
			},
			redTeam: {
				totalGold: 56915,
				inhibitors: 0,
				towers: 3,
				barons: 1,
				totalKills: 13,
				dragons: ['mountain'],
				participants: [
					{
						participantId: 6,
						totalGold: 10849,
						level: 16,
						kills: 2,
						deaths: 4,
						assists: 5,
						creepScore: 227,
						currentHealth: 0,
						maxHealth: 2976,
					},
					{
						participantId: 7,
						totalGold: 9867,
						level: 14,
						kills: 0,
						deaths: 3,
						assists: 7,
						creepScore: 159,
						currentHealth: 3960,
						maxHealth: 4045,
					},
					{
						participantId: 8,
						totalGold: 13445,
						level: 16,
						kills: 3,
						deaths: 2,
						assists: 3,
						creepScore: 283,
						currentHealth: 0,
						maxHealth: 2167,
					},
					{
						participantId: 9,
						totalGold: 13517,
						level: 15,
						kills: 5,
						deaths: 2,
						assists: 4,
						creepScore: 274,
						currentHealth: 494,
						maxHealth: 2084,
					},
					{
						participantId: 10,
						totalGold: 9237,
						level: 13,
						kills: 3,
						deaths: 4,
						assists: 3,
						creepScore: 34,
						currentHealth: 785,
						maxHealth: 1969,
					},
				],
			},
		},
		{
			rfc460Timestamp: '2023-11-11T12:09:43.200Z',
			gameState: 'in_game',
			blueTeam: {
				totalGold: 57723,
				inhibitors: 1,
				towers: 6,
				barons: 1,
				totalKills: 15,
				dragons: ['cloud', 'infernal', 'mountain', 'mountain'],
				participants: [
					{
						participantId: 1,
						totalGold: 9797,
						level: 15,
						kills: 0,
						deaths: 5,
						assists: 5,
						creepScore: 220,
						currentHealth: 0,
						maxHealth: 3981,
					},
					{
						participantId: 2,
						totalGold: 9845,
						level: 14,
						kills: 0,
						deaths: 3,
						assists: 9,
						creepScore: 155,
						currentHealth: 2727,
						maxHealth: 2727,
					},
					{
						participantId: 3,
						totalGold: 14965,
						level: 18,
						kills: 5,
						deaths: 2,
						assists: 3,
						creepScore: 313,
						currentHealth: 641,
						maxHealth: 2923,
					},
					{
						participantId: 4,
						totalGold: 15204,
						level: 15,
						kills: 9,
						deaths: 2,
						assists: 3,
						creepScore: 288,
						currentHealth: 0,
						maxHealth: 2112,
					},
					{
						participantId: 5,
						totalGold: 7912,
						level: 14,
						kills: 1,
						deaths: 1,
						assists: 10,
						creepScore: 36,
						currentHealth: 842,
						maxHealth: 2331,
					},
				],
			},
			redTeam: {
				totalGold: 56925,
				inhibitors: 0,
				towers: 3,
				barons: 1,
				totalKills: 13,
				dragons: ['mountain'],
				participants: [
					{
						participantId: 6,
						totalGold: 10851,
						level: 16,
						kills: 2,
						deaths: 4,
						assists: 5,
						creepScore: 227,
						currentHealth: 0,
						maxHealth: 2976,
					},
					{
						participantId: 7,
						totalGold: 9869,
						level: 14,
						kills: 0,
						deaths: 3,
						assists: 7,
						creepScore: 159,
						currentHealth: 3560,
						maxHealth: 3582,
					},
					{
						participantId: 8,
						totalGold: 13447,
						level: 16,
						kills: 3,
						deaths: 2,
						assists: 3,
						creepScore: 283,
						currentHealth: 2167,
						maxHealth: 2167,
					},
					{
						participantId: 9,
						totalGold: 13519,
						level: 15,
						kills: 5,
						deaths: 2,
						assists: 4,
						creepScore: 274,
						currentHealth: 496,
						maxHealth: 2084,
					},
					{
						participantId: 10,
						totalGold: 9239,
						level: 13,
						kills: 3,
						deaths: 4,
						assists: 3,
						creepScore: 34,
						currentHealth: 908,
						maxHealth: 1969,
					},
				],
			},
		},
		{
			rfc460Timestamp: '2023-11-11T12:09:43.729Z',
			gameState: 'in_game',
			blueTeam: {
				totalGold: 57723,
				inhibitors: 1,
				towers: 6,
				barons: 1,
				totalKills: 15,
				dragons: ['cloud', 'infernal', 'mountain', 'mountain'],
				participants: [
					{
						participantId: 1,
						totalGold: 9797,
						level: 15,
						kills: 0,
						deaths: 5,
						assists: 5,
						creepScore: 220,
						currentHealth: 0,
						maxHealth: 3981,
					},
					{
						participantId: 2,
						totalGold: 9845,
						level: 14,
						kills: 0,
						deaths: 3,
						assists: 9,
						creepScore: 155,
						currentHealth: 2727,
						maxHealth: 2727,
					},
					{
						participantId: 3,
						totalGold: 14965,
						level: 18,
						kills: 5,
						deaths: 2,
						assists: 3,
						creepScore: 313,
						currentHealth: 641,
						maxHealth: 2923,
					},
					{
						participantId: 4,
						totalGold: 15204,
						level: 15,
						kills: 9,
						deaths: 2,
						assists: 3,
						creepScore: 288,
						currentHealth: 0,
						maxHealth: 2112,
					},
					{
						participantId: 5,
						totalGold: 7912,
						level: 14,
						kills: 1,
						deaths: 1,
						assists: 10,
						creepScore: 36,
						currentHealth: 842,
						maxHealth: 2331,
					},
				],
			},
			redTeam: {
				totalGold: 56925,
				inhibitors: 0,
				towers: 3,
				barons: 1,
				totalKills: 13,
				dragons: ['mountain'],
				participants: [
					{
						participantId: 6,
						totalGold: 10851,
						level: 16,
						kills: 2,
						deaths: 4,
						assists: 5,
						creepScore: 227,
						currentHealth: 0,
						maxHealth: 2976,
					},
					{
						participantId: 7,
						totalGold: 9869,
						level: 14,
						kills: 0,
						deaths: 3,
						assists: 7,
						creepScore: 159,
						currentHealth: 3560,
						maxHealth: 3582,
					},
					{
						participantId: 8,
						totalGold: 13447,
						level: 16,
						kills: 3,
						deaths: 2,
						assists: 3,
						creepScore: 283,
						currentHealth: 2167,
						maxHealth: 2167,
					},
					{
						participantId: 9,
						totalGold: 13519,
						level: 15,
						kills: 5,
						deaths: 2,
						assists: 4,
						creepScore: 274,
						currentHealth: 496,
						maxHealth: 2084,
					},
					{
						participantId: 10,
						totalGold: 9239,
						level: 13,
						kills: 3,
						deaths: 4,
						assists: 3,
						creepScore: 34,
						currentHealth: 908,
						maxHealth: 1969,
					},
				],
			},
		},
		{
			rfc460Timestamp: '2023-11-11T12:09:44.033Z',
			gameState: 'in_game',
			blueTeam: {
				totalGold: 57723,
				inhibitors: 1,
				towers: 6,
				barons: 1,
				totalKills: 15,
				dragons: ['cloud', 'infernal', 'mountain', 'mountain'],
				participants: [
					{
						participantId: 1,
						totalGold: 9797,
						level: 15,
						kills: 0,
						deaths: 5,
						assists: 5,
						creepScore: 220,
						currentHealth: 0,
						maxHealth: 3981,
					},
					{
						participantId: 2,
						totalGold: 9845,
						level: 14,
						kills: 0,
						deaths: 3,
						assists: 9,
						creepScore: 155,
						currentHealth: 2727,
						maxHealth: 2727,
					},
					{
						participantId: 3,
						totalGold: 14965,
						level: 18,
						kills: 5,
						deaths: 2,
						assists: 3,
						creepScore: 313,
						currentHealth: 641,
						maxHealth: 2923,
					},
					{
						participantId: 4,
						totalGold: 15204,
						level: 15,
						kills: 9,
						deaths: 2,
						assists: 3,
						creepScore: 288,
						currentHealth: 0,
						maxHealth: 2112,
					},
					{
						participantId: 5,
						totalGold: 7912,
						level: 14,
						kills: 1,
						deaths: 1,
						assists: 10,
						creepScore: 36,
						currentHealth: 842,
						maxHealth: 2331,
					},
				],
			},
			redTeam: {
				totalGold: 56925,
				inhibitors: 0,
				towers: 3,
				barons: 1,
				totalKills: 13,
				dragons: ['mountain'],
				participants: [
					{
						participantId: 6,
						totalGold: 10851,
						level: 16,
						kills: 2,
						deaths: 4,
						assists: 5,
						creepScore: 227,
						currentHealth: 0,
						maxHealth: 2976,
					},
					{
						participantId: 7,
						totalGold: 9869,
						level: 14,
						kills: 0,
						deaths: 3,
						assists: 7,
						creepScore: 159,
						currentHealth: 3560,
						maxHealth: 3582,
					},
					{
						participantId: 8,
						totalGold: 13447,
						level: 16,
						kills: 3,
						deaths: 2,
						assists: 3,
						creepScore: 283,
						currentHealth: 2167,
						maxHealth: 2167,
					},
					{
						participantId: 9,
						totalGold: 13519,
						level: 15,
						kills: 5,
						deaths: 2,
						assists: 4,
						creepScore: 274,
						currentHealth: 496,
						maxHealth: 2084,
					},
					{
						participantId: 10,
						totalGold: 9239,
						level: 13,
						kills: 3,
						deaths: 4,
						assists: 3,
						creepScore: 34,
						currentHealth: 908,
						maxHealth: 1969,
					},
				],
			},
		},
		{
			rfc460Timestamp: '2023-11-11T12:09:44.034Z',
			gameState: 'in_game',
			blueTeam: {
				totalGold: 57723,
				inhibitors: 1,
				towers: 6,
				barons: 1,
				totalKills: 15,
				dragons: ['cloud', 'infernal', 'mountain', 'mountain'],
				participants: [
					{
						participantId: 1,
						totalGold: 9797,
						level: 15,
						kills: 0,
						deaths: 5,
						assists: 5,
						creepScore: 220,
						currentHealth: 0,
						maxHealth: 3981,
					},
					{
						participantId: 2,
						totalGold: 9845,
						level: 14,
						kills: 0,
						deaths: 3,
						assists: 9,
						creepScore: 155,
						currentHealth: 2727,
						maxHealth: 2727,
					},
					{
						participantId: 3,
						totalGold: 14965,
						level: 18,
						kills: 5,
						deaths: 2,
						assists: 3,
						creepScore: 313,
						currentHealth: 641,
						maxHealth: 2923,
					},
					{
						participantId: 4,
						totalGold: 15204,
						level: 15,
						kills: 9,
						deaths: 2,
						assists: 3,
						creepScore: 288,
						currentHealth: 0,
						maxHealth: 2112,
					},
					{
						participantId: 5,
						totalGold: 7912,
						level: 14,
						kills: 1,
						deaths: 1,
						assists: 10,
						creepScore: 36,
						currentHealth: 842,
						maxHealth: 2331,
					},
				],
			},
			redTeam: {
				totalGold: 56925,
				inhibitors: 0,
				towers: 3,
				barons: 1,
				totalKills: 13,
				dragons: ['mountain'],
				participants: [
					{
						participantId: 6,
						totalGold: 10851,
						level: 16,
						kills: 2,
						deaths: 4,
						assists: 5,
						creepScore: 227,
						currentHealth: 0,
						maxHealth: 2976,
					},
					{
						participantId: 7,
						totalGold: 9869,
						level: 14,
						kills: 0,
						deaths: 3,
						assists: 7,
						creepScore: 159,
						currentHealth: 3560,
						maxHealth: 3582,
					},
					{
						participantId: 8,
						totalGold: 13447,
						level: 16,
						kills: 3,
						deaths: 2,
						assists: 3,
						creepScore: 283,
						currentHealth: 2167,
						maxHealth: 2167,
					},
					{
						participantId: 9,
						totalGold: 13519,
						level: 15,
						kills: 5,
						deaths: 2,
						assists: 4,
						creepScore: 274,
						currentHealth: 496,
						maxHealth: 2084,
					},
					{
						participantId: 10,
						totalGold: 9239,
						level: 13,
						kills: 3,
						deaths: 4,
						assists: 3,
						creepScore: 34,
						currentHealth: 908,
						maxHealth: 1969,
					},
				],
			},
		},
		{
			rfc460Timestamp: '2023-11-11T12:09:44.035Z',
			gameState: 'in_game',
			blueTeam: {
				totalGold: 57723,
				inhibitors: 1,
				towers: 6,
				barons: 1,
				totalKills: 15,
				dragons: ['cloud', 'infernal', 'mountain', 'mountain'],
				participants: [
					{
						participantId: 1,
						totalGold: 9797,
						level: 15,
						kills: 0,
						deaths: 5,
						assists: 5,
						creepScore: 220,
						currentHealth: 0,
						maxHealth: 3981,
					},
					{
						participantId: 2,
						totalGold: 9845,
						level: 14,
						kills: 0,
						deaths: 3,
						assists: 9,
						creepScore: 155,
						currentHealth: 2727,
						maxHealth: 2727,
					},
					{
						participantId: 3,
						totalGold: 14965,
						level: 18,
						kills: 5,
						deaths: 2,
						assists: 3,
						creepScore: 313,
						currentHealth: 641,
						maxHealth: 2923,
					},
					{
						participantId: 4,
						totalGold: 15204,
						level: 15,
						kills: 9,
						deaths: 2,
						assists: 3,
						creepScore: 288,
						currentHealth: 0,
						maxHealth: 2112,
					},
					{
						participantId: 5,
						totalGold: 7912,
						level: 14,
						kills: 1,
						deaths: 1,
						assists: 10,
						creepScore: 36,
						currentHealth: 842,
						maxHealth: 2331,
					},
				],
			},
			redTeam: {
				totalGold: 56925,
				inhibitors: 0,
				towers: 3,
				barons: 1,
				totalKills: 13,
				dragons: ['mountain'],
				participants: [
					{
						participantId: 6,
						totalGold: 10851,
						level: 16,
						kills: 2,
						deaths: 4,
						assists: 5,
						creepScore: 227,
						currentHealth: 0,
						maxHealth: 2976,
					},
					{
						participantId: 7,
						totalGold: 9869,
						level: 14,
						kills: 0,
						deaths: 3,
						assists: 7,
						creepScore: 159,
						currentHealth: 3560,
						maxHealth: 3582,
					},
					{
						participantId: 8,
						totalGold: 13447,
						level: 16,
						kills: 3,
						deaths: 2,
						assists: 3,
						creepScore: 283,
						currentHealth: 2167,
						maxHealth: 2167,
					},
					{
						participantId: 9,
						totalGold: 13519,
						level: 15,
						kills: 5,
						deaths: 2,
						assists: 4,
						creepScore: 274,
						currentHealth: 496,
						maxHealth: 2084,
					},
					{
						participantId: 10,
						totalGold: 9239,
						level: 13,
						kills: 3,
						deaths: 4,
						assists: 3,
						creepScore: 34,
						currentHealth: 908,
						maxHealth: 1969,
					},
				],
			},
		},
		{
			rfc460Timestamp: '2023-11-11T12:09:44.200Z',
			gameState: 'in_game',
			blueTeam: {
				totalGold: 57733,
				inhibitors: 1,
				towers: 6,
				barons: 1,
				totalKills: 15,
				dragons: ['cloud', 'infernal', 'mountain', 'mountain'],
				participants: [
					{
						participantId: 1,
						totalGold: 9799,
						level: 15,
						kills: 0,
						deaths: 5,
						assists: 5,
						creepScore: 220,
						currentHealth: 0,
						maxHealth: 3981,
					},
					{
						participantId: 2,
						totalGold: 9847,
						level: 14,
						kills: 0,
						deaths: 3,
						assists: 9,
						creepScore: 155,
						currentHealth: 2727,
						maxHealth: 2727,
					},
					{
						participantId: 3,
						totalGold: 14967,
						level: 18,
						kills: 5,
						deaths: 2,
						assists: 3,
						creepScore: 313,
						currentHealth: 645,
						maxHealth: 2923,
					},
					{
						participantId: 4,
						totalGold: 15206,
						level: 15,
						kills: 9,
						deaths: 2,
						assists: 3,
						creepScore: 288,
						currentHealth: 0,
						maxHealth: 2112,
					},
					{
						participantId: 5,
						totalGold: 7914,
						level: 14,
						kills: 1,
						deaths: 1,
						assists: 10,
						creepScore: 36,
						currentHealth: 852,
						maxHealth: 2331,
					},
				],
			},
			redTeam: {
				totalGold: 56935,
				inhibitors: 0,
				towers: 3,
				barons: 1,
				totalKills: 13,
				dragons: ['mountain'],
				participants: [
					{
						participantId: 6,
						totalGold: 10853,
						level: 16,
						kills: 2,
						deaths: 4,
						assists: 5,
						creepScore: 227,
						currentHealth: 0,
						maxHealth: 2976,
					},
					{
						participantId: 7,
						totalGold: 9871,
						level: 14,
						kills: 0,
						deaths: 3,
						assists: 7,
						creepScore: 159,
						currentHealth: 3525,
						maxHealth: 3582,
					},
					{
						participantId: 8,
						totalGold: 13449,
						level: 16,
						kills: 3,
						deaths: 2,
						assists: 3,
						creepScore: 283,
						currentHealth: 2167,
						maxHealth: 2167,
					},
					{
						participantId: 9,
						totalGold: 13521,
						level: 15,
						kills: 5,
						deaths: 2,
						assists: 4,
						creepScore: 274,
						currentHealth: 499,
						maxHealth: 2084,
					},
					{
						participantId: 10,
						totalGold: 9241,
						level: 13,
						kills: 3,
						deaths: 4,
						assists: 3,
						creepScore: 34,
						currentHealth: 930,
						maxHealth: 1969,
					},
				],
			},
		},
		{
			rfc460Timestamp: '2023-11-11T12:09:44.333Z',
			gameState: 'in_game',
			blueTeam: {
				totalGold: 57733,
				inhibitors: 1,
				towers: 6,
				barons: 1,
				totalKills: 15,
				dragons: ['cloud', 'infernal', 'mountain', 'mountain'],
				participants: [
					{
						participantId: 1,
						totalGold: 9799,
						level: 15,
						kills: 0,
						deaths: 5,
						assists: 5,
						creepScore: 220,
						currentHealth: 0,
						maxHealth: 3981,
					},
					{
						participantId: 2,
						totalGold: 9847,
						level: 14,
						kills: 0,
						deaths: 3,
						assists: 9,
						creepScore: 155,
						currentHealth: 2727,
						maxHealth: 2727,
					},
					{
						participantId: 3,
						totalGold: 14967,
						level: 18,
						kills: 5,
						deaths: 2,
						assists: 3,
						creepScore: 313,
						currentHealth: 645,
						maxHealth: 2923,
					},
					{
						participantId: 4,
						totalGold: 15206,
						level: 15,
						kills: 9,
						deaths: 2,
						assists: 3,
						creepScore: 288,
						currentHealth: 0,
						maxHealth: 2112,
					},
					{
						participantId: 5,
						totalGold: 7914,
						level: 14,
						kills: 1,
						deaths: 1,
						assists: 10,
						creepScore: 36,
						currentHealth: 852,
						maxHealth: 2331,
					},
				],
			},
			redTeam: {
				totalGold: 56935,
				inhibitors: 0,
				towers: 3,
				barons: 1,
				totalKills: 13,
				dragons: ['mountain'],
				participants: [
					{
						participantId: 6,
						totalGold: 10853,
						level: 16,
						kills: 2,
						deaths: 4,
						assists: 5,
						creepScore: 227,
						currentHealth: 0,
						maxHealth: 2976,
					},
					{
						participantId: 7,
						totalGold: 9871,
						level: 14,
						kills: 0,
						deaths: 3,
						assists: 7,
						creepScore: 159,
						currentHealth: 3525,
						maxHealth: 3582,
					},
					{
						participantId: 8,
						totalGold: 13449,
						level: 16,
						kills: 3,
						deaths: 2,
						assists: 3,
						creepScore: 283,
						currentHealth: 2167,
						maxHealth: 2167,
					},
					{
						participantId: 9,
						totalGold: 13521,
						level: 15,
						kills: 5,
						deaths: 2,
						assists: 4,
						creepScore: 274,
						currentHealth: 499,
						maxHealth: 2084,
					},
					{
						participantId: 10,
						totalGold: 9241,
						level: 13,
						kills: 3,
						deaths: 4,
						assists: 3,
						creepScore: 34,
						currentHealth: 930,
						maxHealth: 1969,
					},
				],
			},
		},
		{
			rfc460Timestamp: '2023-11-11T12:09:44.567Z',
			gameState: 'in_game',
			blueTeam: {
				totalGold: 57733,
				inhibitors: 1,
				towers: 6,
				barons: 1,
				totalKills: 15,
				dragons: ['cloud', 'infernal', 'mountain', 'mountain'],
				participants: [
					{
						participantId: 1,
						totalGold: 9799,
						level: 15,
						kills: 0,
						deaths: 5,
						assists: 5,
						creepScore: 220,
						currentHealth: 0,
						maxHealth: 3981,
					},
					{
						participantId: 2,
						totalGold: 9847,
						level: 14,
						kills: 0,
						deaths: 3,
						assists: 9,
						creepScore: 155,
						currentHealth: 2727,
						maxHealth: 2727,
					},
					{
						participantId: 3,
						totalGold: 14967,
						level: 18,
						kills: 5,
						deaths: 2,
						assists: 3,
						creepScore: 313,
						currentHealth: 645,
						maxHealth: 2923,
					},
					{
						participantId: 4,
						totalGold: 15206,
						level: 15,
						kills: 9,
						deaths: 2,
						assists: 3,
						creepScore: 288,
						currentHealth: 0,
						maxHealth: 2112,
					},
					{
						participantId: 5,
						totalGold: 7914,
						level: 14,
						kills: 1,
						deaths: 1,
						assists: 10,
						creepScore: 36,
						currentHealth: 852,
						maxHealth: 2331,
					},
				],
			},
			redTeam: {
				totalGold: 56935,
				inhibitors: 0,
				towers: 3,
				barons: 1,
				totalKills: 13,
				dragons: ['mountain'],
				participants: [
					{
						participantId: 6,
						totalGold: 10853,
						level: 16,
						kills: 2,
						deaths: 4,
						assists: 5,
						creepScore: 227,
						currentHealth: 0,
						maxHealth: 2976,
					},
					{
						participantId: 7,
						totalGold: 9871,
						level: 14,
						kills: 0,
						deaths: 3,
						assists: 7,
						creepScore: 159,
						currentHealth: 3525,
						maxHealth: 3582,
					},
					{
						participantId: 8,
						totalGold: 13449,
						level: 16,
						kills: 3,
						deaths: 2,
						assists: 3,
						creepScore: 283,
						currentHealth: 2167,
						maxHealth: 2167,
					},
					{
						participantId: 9,
						totalGold: 13521,
						level: 15,
						kills: 5,
						deaths: 2,
						assists: 4,
						creepScore: 274,
						currentHealth: 499,
						maxHealth: 2084,
					},
					{
						participantId: 10,
						totalGold: 9241,
						level: 13,
						kills: 3,
						deaths: 4,
						assists: 3,
						creepScore: 34,
						currentHealth: 930,
						maxHealth: 1969,
					},
				],
			},
		},
		{
			rfc460Timestamp: '2023-11-11T12:09:44.569Z',
			gameState: 'in_game',
			blueTeam: {
				totalGold: 57733,
				inhibitors: 1,
				towers: 6,
				barons: 1,
				totalKills: 15,
				dragons: ['cloud', 'infernal', 'mountain', 'mountain'],
				participants: [
					{
						participantId: 1,
						totalGold: 9799,
						level: 15,
						kills: 0,
						deaths: 5,
						assists: 5,
						creepScore: 220,
						currentHealth: 0,
						maxHealth: 3981,
					},
					{
						participantId: 2,
						totalGold: 9847,
						level: 14,
						kills: 0,
						deaths: 3,
						assists: 9,
						creepScore: 155,
						currentHealth: 2727,
						maxHealth: 2727,
					},
					{
						participantId: 3,
						totalGold: 14967,
						level: 18,
						kills: 5,
						deaths: 2,
						assists: 3,
						creepScore: 313,
						currentHealth: 645,
						maxHealth: 2923,
					},
					{
						participantId: 4,
						totalGold: 15206,
						level: 15,
						kills: 9,
						deaths: 2,
						assists: 3,
						creepScore: 288,
						currentHealth: 0,
						maxHealth: 2112,
					},
					{
						participantId: 5,
						totalGold: 7914,
						level: 14,
						kills: 1,
						deaths: 1,
						assists: 10,
						creepScore: 36,
						currentHealth: 852,
						maxHealth: 2331,
					},
				],
			},
			redTeam: {
				totalGold: 56935,
				inhibitors: 0,
				towers: 3,
				barons: 1,
				totalKills: 13,
				dragons: ['mountain'],
				participants: [
					{
						participantId: 6,
						totalGold: 10853,
						level: 16,
						kills: 2,
						deaths: 4,
						assists: 5,
						creepScore: 227,
						currentHealth: 0,
						maxHealth: 2976,
					},
					{
						participantId: 7,
						totalGold: 9871,
						level: 14,
						kills: 0,
						deaths: 3,
						assists: 7,
						creepScore: 159,
						currentHealth: 3525,
						maxHealth: 3582,
					},
					{
						participantId: 8,
						totalGold: 13449,
						level: 16,
						kills: 3,
						deaths: 2,
						assists: 3,
						creepScore: 283,
						currentHealth: 2167,
						maxHealth: 2167,
					},
					{
						participantId: 9,
						totalGold: 13521,
						level: 15,
						kills: 5,
						deaths: 2,
						assists: 4,
						creepScore: 274,
						currentHealth: 499,
						maxHealth: 2084,
					},
					{
						participantId: 10,
						totalGold: 9241,
						level: 13,
						kills: 3,
						deaths: 4,
						assists: 3,
						creepScore: 34,
						currentHealth: 930,
						maxHealth: 1969,
					},
				],
			},
		},
		{
			rfc460Timestamp: '2023-11-11T12:09:44.603Z',
			gameState: 'in_game',
			blueTeam: {
				totalGold: 57733,
				inhibitors: 1,
				towers: 6,
				barons: 1,
				totalKills: 15,
				dragons: ['cloud', 'infernal', 'mountain', 'mountain'],
				participants: [
					{
						participantId: 1,
						totalGold: 9799,
						level: 15,
						kills: 0,
						deaths: 5,
						assists: 5,
						creepScore: 220,
						currentHealth: 0,
						maxHealth: 3981,
					},
					{
						participantId: 2,
						totalGold: 9847,
						level: 14,
						kills: 0,
						deaths: 3,
						assists: 9,
						creepScore: 155,
						currentHealth: 2727,
						maxHealth: 2727,
					},
					{
						participantId: 3,
						totalGold: 14967,
						level: 18,
						kills: 5,
						deaths: 2,
						assists: 3,
						creepScore: 313,
						currentHealth: 645,
						maxHealth: 2923,
					},
					{
						participantId: 4,
						totalGold: 15206,
						level: 15,
						kills: 9,
						deaths: 2,
						assists: 3,
						creepScore: 288,
						currentHealth: 0,
						maxHealth: 2112,
					},
					{
						participantId: 5,
						totalGold: 7914,
						level: 14,
						kills: 1,
						deaths: 1,
						assists: 10,
						creepScore: 36,
						currentHealth: 852,
						maxHealth: 2331,
					},
				],
			},
			redTeam: {
				totalGold: 56935,
				inhibitors: 0,
				towers: 3,
				barons: 1,
				totalKills: 13,
				dragons: ['mountain'],
				participants: [
					{
						participantId: 6,
						totalGold: 10853,
						level: 16,
						kills: 2,
						deaths: 4,
						assists: 5,
						creepScore: 227,
						currentHealth: 0,
						maxHealth: 2976,
					},
					{
						participantId: 7,
						totalGold: 9871,
						level: 14,
						kills: 0,
						deaths: 3,
						assists: 7,
						creepScore: 159,
						currentHealth: 3525,
						maxHealth: 3582,
					},
					{
						participantId: 8,
						totalGold: 13449,
						level: 16,
						kills: 3,
						deaths: 2,
						assists: 3,
						creepScore: 283,
						currentHealth: 2167,
						maxHealth: 2167,
					},
					{
						participantId: 9,
						totalGold: 13521,
						level: 15,
						kills: 5,
						deaths: 2,
						assists: 4,
						creepScore: 274,
						currentHealth: 499,
						maxHealth: 2084,
					},
					{
						participantId: 10,
						totalGold: 9241,
						level: 13,
						kills: 3,
						deaths: 4,
						assists: 3,
						creepScore: 34,
						currentHealth: 930,
						maxHealth: 1969,
					},
				],
			},
		},
		{
			rfc460Timestamp: '2023-11-11T12:09:45.071Z',
			gameState: 'in_game',
			blueTeam: {
				totalGold: 57733,
				inhibitors: 1,
				towers: 6,
				barons: 1,
				totalKills: 15,
				dragons: ['cloud', 'infernal', 'mountain', 'mountain'],
				participants: [
					{
						participantId: 1,
						totalGold: 9799,
						level: 15,
						kills: 0,
						deaths: 5,
						assists: 5,
						creepScore: 220,
						currentHealth: 0,
						maxHealth: 3981,
					},
					{
						participantId: 2,
						totalGold: 9847,
						level: 14,
						kills: 0,
						deaths: 3,
						assists: 9,
						creepScore: 155,
						currentHealth: 2727,
						maxHealth: 2727,
					},
					{
						participantId: 3,
						totalGold: 14967,
						level: 18,
						kills: 5,
						deaths: 2,
						assists: 3,
						creepScore: 313,
						currentHealth: 645,
						maxHealth: 2923,
					},
					{
						participantId: 4,
						totalGold: 15206,
						level: 15,
						kills: 9,
						deaths: 2,
						assists: 3,
						creepScore: 288,
						currentHealth: 0,
						maxHealth: 2112,
					},
					{
						participantId: 5,
						totalGold: 7914,
						level: 14,
						kills: 1,
						deaths: 1,
						assists: 10,
						creepScore: 36,
						currentHealth: 852,
						maxHealth: 2331,
					},
				],
			},
			redTeam: {
				totalGold: 56935,
				inhibitors: 0,
				towers: 3,
				barons: 1,
				totalKills: 13,
				dragons: ['mountain'],
				participants: [
					{
						participantId: 6,
						totalGold: 10853,
						level: 16,
						kills: 2,
						deaths: 4,
						assists: 5,
						creepScore: 227,
						currentHealth: 0,
						maxHealth: 2976,
					},
					{
						participantId: 7,
						totalGold: 9871,
						level: 14,
						kills: 0,
						deaths: 3,
						assists: 7,
						creepScore: 159,
						currentHealth: 3525,
						maxHealth: 3582,
					},
					{
						participantId: 8,
						totalGold: 13449,
						level: 16,
						kills: 3,
						deaths: 2,
						assists: 3,
						creepScore: 283,
						currentHealth: 2167,
						maxHealth: 2167,
					},
					{
						participantId: 9,
						totalGold: 13521,
						level: 15,
						kills: 5,
						deaths: 2,
						assists: 4,
						creepScore: 274,
						currentHealth: 499,
						maxHealth: 2084,
					},
					{
						participantId: 10,
						totalGold: 9241,
						level: 13,
						kills: 3,
						deaths: 4,
						assists: 3,
						creepScore: 34,
						currentHealth: 930,
						maxHealth: 1969,
					},
				],
			},
		},
		{
			rfc460Timestamp: '2023-11-11T12:09:45.206Z',
			gameState: 'in_game',
			blueTeam: {
				totalGold: 57744,
				inhibitors: 1,
				towers: 6,
				barons: 1,
				totalKills: 15,
				dragons: ['cloud', 'infernal', 'mountain', 'mountain'],
				participants: [
					{
						participantId: 1,
						totalGold: 9801,
						level: 15,
						kills: 0,
						deaths: 5,
						assists: 5,
						creepScore: 220,
						currentHealth: 0,
						maxHealth: 3981,
					},
					{
						participantId: 2,
						totalGold: 9849,
						level: 14,
						kills: 0,
						deaths: 3,
						assists: 9,
						creepScore: 155,
						currentHealth: 2727,
						maxHealth: 2727,
					},
					{
						participantId: 3,
						totalGold: 14969,
						level: 18,
						kills: 5,
						deaths: 2,
						assists: 3,
						creepScore: 313,
						currentHealth: 649,
						maxHealth: 2923,
					},
					{
						participantId: 4,
						totalGold: 15208,
						level: 15,
						kills: 9,
						deaths: 2,
						assists: 3,
						creepScore: 288,
						currentHealth: 0,
						maxHealth: 2112,
					},
					{
						participantId: 5,
						totalGold: 7917,
						level: 14,
						kills: 1,
						deaths: 1,
						assists: 10,
						creepScore: 36,
						currentHealth: 862,
						maxHealth: 2331,
					},
				],
			},
			redTeam: {
				totalGold: 56988,
				inhibitors: 0,
				towers: 3,
				barons: 1,
				totalKills: 13,
				dragons: ['mountain'],
				participants: [
					{
						participantId: 6,
						totalGold: 10855,
						level: 16,
						kills: 2,
						deaths: 4,
						assists: 5,
						creepScore: 227,
						currentHealth: 2976,
						maxHealth: 2976,
					},
					{
						participantId: 7,
						totalGold: 9873,
						level: 14,
						kills: 0,
						deaths: 3,
						assists: 7,
						creepScore: 159,
						currentHealth: 3436,
						maxHealth: 3582,
					},
					{
						participantId: 8,
						totalGold: 13451,
						level: 16,
						kills: 3,
						deaths: 2,
						assists: 3,
						creepScore: 283,
						currentHealth: 2167,
						maxHealth: 2167,
					},
					{
						participantId: 9,
						totalGold: 13523,
						level: 15,
						kills: 5,
						deaths: 2,
						assists: 4,
						creepScore: 274,
						currentHealth: 501,
						maxHealth: 2084,
					},
					{
						participantId: 10,
						totalGold: 9286,
						level: 13,
						kills: 3,
						deaths: 4,
						assists: 3,
						creepScore: 37,
						currentHealth: 952,
						maxHealth: 1969,
					},
				],
			},
		},
		{
			rfc460Timestamp: '2023-11-11T12:09:46.164Z',
			gameState: 'in_game',
			blueTeam: {
				totalGold: 57744,
				inhibitors: 1,
				towers: 6,
				barons: 1,
				totalKills: 15,
				dragons: ['cloud', 'infernal', 'mountain', 'mountain'],
				participants: [
					{
						participantId: 1,
						totalGold: 9801,
						level: 15,
						kills: 0,
						deaths: 5,
						assists: 5,
						creepScore: 220,
						currentHealth: 0,
						maxHealth: 3981,
					},
					{
						participantId: 2,
						totalGold: 9849,
						level: 14,
						kills: 0,
						deaths: 3,
						assists: 9,
						creepScore: 155,
						currentHealth: 2727,
						maxHealth: 2727,
					},
					{
						participantId: 3,
						totalGold: 14969,
						level: 18,
						kills: 5,
						deaths: 2,
						assists: 3,
						creepScore: 313,
						currentHealth: 649,
						maxHealth: 2923,
					},
					{
						participantId: 4,
						totalGold: 15208,
						level: 15,
						kills: 9,
						deaths: 2,
						assists: 3,
						creepScore: 288,
						currentHealth: 0,
						maxHealth: 2112,
					},
					{
						participantId: 5,
						totalGold: 7917,
						level: 14,
						kills: 1,
						deaths: 1,
						assists: 10,
						creepScore: 36,
						currentHealth: 862,
						maxHealth: 2331,
					},
				],
			},
			redTeam: {
				totalGold: 56988,
				inhibitors: 0,
				towers: 3,
				barons: 1,
				totalKills: 13,
				dragons: ['mountain'],
				participants: [
					{
						participantId: 6,
						totalGold: 10855,
						level: 16,
						kills: 2,
						deaths: 4,
						assists: 5,
						creepScore: 227,
						currentHealth: 2976,
						maxHealth: 2976,
					},
					{
						participantId: 7,
						totalGold: 9873,
						level: 14,
						kills: 0,
						deaths: 3,
						assists: 7,
						creepScore: 159,
						currentHealth: 3436,
						maxHealth: 3582,
					},
					{
						participantId: 8,
						totalGold: 13451,
						level: 16,
						kills: 3,
						deaths: 2,
						assists: 3,
						creepScore: 283,
						currentHealth: 2167,
						maxHealth: 2167,
					},
					{
						participantId: 9,
						totalGold: 13523,
						level: 15,
						kills: 5,
						deaths: 2,
						assists: 4,
						creepScore: 274,
						currentHealth: 501,
						maxHealth: 2084,
					},
					{
						participantId: 10,
						totalGold: 9286,
						level: 13,
						kills: 3,
						deaths: 4,
						assists: 3,
						creepScore: 37,
						currentHealth: 952,
						maxHealth: 1969,
					},
				],
			},
		},
		{
			rfc460Timestamp: '2023-11-11T12:09:46.200Z',
			gameState: 'in_game',
			blueTeam: {
				totalGold: 57754,
				inhibitors: 1,
				towers: 6,
				barons: 1,
				totalKills: 15,
				dragons: ['cloud', 'infernal', 'mountain', 'mountain'],
				participants: [
					{
						participantId: 1,
						totalGold: 9803,
						level: 15,
						kills: 0,
						deaths: 5,
						assists: 5,
						creepScore: 220,
						currentHealth: 0,
						maxHealth: 3981,
					},
					{
						participantId: 2,
						totalGold: 9851,
						level: 14,
						kills: 0,
						deaths: 3,
						assists: 9,
						creepScore: 155,
						currentHealth: 2727,
						maxHealth: 2727,
					},
					{
						participantId: 3,
						totalGold: 14971,
						level: 18,
						kills: 5,
						deaths: 2,
						assists: 3,
						creepScore: 313,
						currentHealth: 653,
						maxHealth: 2923,
					},
					{
						participantId: 4,
						totalGold: 15210,
						level: 15,
						kills: 9,
						deaths: 2,
						assists: 3,
						creepScore: 288,
						currentHealth: 0,
						maxHealth: 2112,
					},
					{
						participantId: 5,
						totalGold: 7919,
						level: 14,
						kills: 1,
						deaths: 1,
						assists: 10,
						creepScore: 36,
						currentHealth: 871,
						maxHealth: 2331,
					},
				],
			},
			redTeam: {
				totalGold: 57019,
				inhibitors: 0,
				towers: 3,
				barons: 1,
				totalKills: 13,
				dragons: ['mountain'],
				participants: [
					{
						participantId: 6,
						totalGold: 10857,
						level: 16,
						kills: 2,
						deaths: 4,
						assists: 5,
						creepScore: 227,
						currentHealth: 2976,
						maxHealth: 2976,
					},
					{
						participantId: 7,
						totalGold: 9896,
						level: 14,
						kills: 0,
						deaths: 3,
						assists: 7,
						creepScore: 160,
						currentHealth: 3427,
						maxHealth: 3582,
					},
					{
						participantId: 8,
						totalGold: 13453,
						level: 16,
						kills: 3,
						deaths: 2,
						assists: 3,
						creepScore: 283,
						currentHealth: 2167,
						maxHealth: 2167,
					},
					{
						participantId: 9,
						totalGold: 13525,
						level: 15,
						kills: 5,
						deaths: 2,
						assists: 4,
						creepScore: 274,
						currentHealth: 528,
						maxHealth: 2084,
					},
					{
						participantId: 10,
						totalGold: 9288,
						level: 13,
						kills: 3,
						deaths: 4,
						assists: 3,
						creepScore: 37,
						currentHealth: 938,
						maxHealth: 1969,
					},
				],
			},
		},
		{
			rfc460Timestamp: '2023-11-11T12:09:47.203Z',
			gameState: 'in_game',
			blueTeam: {
				totalGold: 57764,
				inhibitors: 1,
				towers: 6,
				barons: 1,
				totalKills: 15,
				dragons: ['cloud', 'infernal', 'mountain', 'mountain'],
				participants: [
					{
						participantId: 1,
						totalGold: 9805,
						level: 15,
						kills: 0,
						deaths: 5,
						assists: 5,
						creepScore: 220,
						currentHealth: 0,
						maxHealth: 3981,
					},
					{
						participantId: 2,
						totalGold: 9853,
						level: 14,
						kills: 0,
						deaths: 3,
						assists: 9,
						creepScore: 155,
						currentHealth: 2727,
						maxHealth: 2727,
					},
					{
						participantId: 3,
						totalGold: 14973,
						level: 18,
						kills: 5,
						deaths: 2,
						assists: 3,
						creepScore: 313,
						currentHealth: 657,
						maxHealth: 2923,
					},
					{
						participantId: 4,
						totalGold: 15212,
						level: 15,
						kills: 9,
						deaths: 2,
						assists: 3,
						creepScore: 288,
						currentHealth: 0,
						maxHealth: 2112,
					},
					{
						participantId: 5,
						totalGold: 7921,
						level: 14,
						kills: 1,
						deaths: 1,
						assists: 10,
						creepScore: 36,
						currentHealth: 881,
						maxHealth: 2331,
					},
				],
			},
			redTeam: {
				totalGold: 57029,
				inhibitors: 0,
				towers: 3,
				barons: 1,
				totalKills: 13,
				dragons: ['mountain'],
				participants: [
					{
						participantId: 6,
						totalGold: 10859,
						level: 16,
						kills: 2,
						deaths: 4,
						assists: 5,
						creepScore: 227,
						currentHealth: 2976,
						maxHealth: 2976,
					},
					{
						participantId: 7,
						totalGold: 9898,
						level: 14,
						kills: 0,
						deaths: 3,
						assists: 7,
						creepScore: 160,
						currentHealth: 3431,
						maxHealth: 3582,
					},
					{
						participantId: 8,
						totalGold: 13455,
						level: 16,
						kills: 3,
						deaths: 2,
						assists: 3,
						creepScore: 283,
						currentHealth: 2167,
						maxHealth: 2167,
					},
					{
						participantId: 9,
						totalGold: 13527,
						level: 15,
						kills: 5,
						deaths: 2,
						assists: 4,
						creepScore: 274,
						currentHealth: 570,
						maxHealth: 2084,
					},
					{
						participantId: 10,
						totalGold: 9290,
						level: 13,
						kills: 3,
						deaths: 4,
						assists: 3,
						creepScore: 37,
						currentHealth: 960,
						maxHealth: 1969,
					},
				],
			},
		},
		{
			rfc460Timestamp: '2023-11-11T12:09:48.204Z',
			gameState: 'in_game',
			blueTeam: {
				totalGold: 57775,
				inhibitors: 1,
				towers: 6,
				barons: 1,
				totalKills: 15,
				dragons: ['cloud', 'infernal', 'mountain', 'mountain'],
				participants: [
					{
						participantId: 1,
						totalGold: 9807,
						level: 15,
						kills: 0,
						deaths: 5,
						assists: 5,
						creepScore: 220,
						currentHealth: 0,
						maxHealth: 3981,
					},
					{
						participantId: 2,
						totalGold: 9855,
						level: 14,
						kills: 0,
						deaths: 3,
						assists: 9,
						creepScore: 155,
						currentHealth: 2727,
						maxHealth: 2727,
					},
					{
						participantId: 3,
						totalGold: 14975,
						level: 18,
						kills: 5,
						deaths: 2,
						assists: 3,
						creepScore: 313,
						currentHealth: 661,
						maxHealth: 2923,
					},
					{
						participantId: 4,
						totalGold: 15214,
						level: 15,
						kills: 9,
						deaths: 2,
						assists: 3,
						creepScore: 288,
						currentHealth: 0,
						maxHealth: 2112,
					},
					{
						participantId: 5,
						totalGold: 7924,
						level: 14,
						kills: 1,
						deaths: 1,
						assists: 10,
						creepScore: 36,
						currentHealth: 891,
						maxHealth: 2331,
					},
				],
			},
			redTeam: {
				totalGold: 57062,
				inhibitors: 0,
				towers: 3,
				barons: 1,
				totalKills: 13,
				dragons: ['mountain'],
				participants: [
					{
						participantId: 6,
						totalGold: 10861,
						level: 16,
						kills: 2,
						deaths: 4,
						assists: 5,
						creepScore: 227,
						currentHealth: 2976,
						maxHealth: 2976,
					},
					{
						participantId: 7,
						totalGold: 9901,
						level: 14,
						kills: 0,
						deaths: 3,
						assists: 7,
						creepScore: 160,
						currentHealth: 3435,
						maxHealth: 3582,
					},
					{
						participantId: 8,
						totalGold: 13457,
						level: 16,
						kills: 3,
						deaths: 2,
						assists: 3,
						creepScore: 283,
						currentHealth: 2167,
						maxHealth: 2167,
					},
					{
						participantId: 9,
						totalGold: 13550,
						level: 15,
						kills: 5,
						deaths: 2,
						assists: 4,
						creepScore: 275,
						currentHealth: 586,
						maxHealth: 2084,
					},
					{
						participantId: 10,
						totalGold: 9293,
						level: 13,
						kills: 3,
						deaths: 4,
						assists: 3,
						creepScore: 37,
						currentHealth: 963,
						maxHealth: 1969,
					},
				],
			},
		},
		{
			rfc460Timestamp: '2023-11-11T12:09:48.437Z',
			gameState: 'in_game',
			blueTeam: {
				totalGold: 57775,
				inhibitors: 1,
				towers: 6,
				barons: 1,
				totalKills: 15,
				dragons: ['cloud', 'infernal', 'mountain', 'mountain'],
				participants: [
					{
						participantId: 1,
						totalGold: 9807,
						level: 15,
						kills: 0,
						deaths: 5,
						assists: 5,
						creepScore: 220,
						currentHealth: 0,
						maxHealth: 3981,
					},
					{
						participantId: 2,
						totalGold: 9855,
						level: 14,
						kills: 0,
						deaths: 3,
						assists: 9,
						creepScore: 155,
						currentHealth: 2727,
						maxHealth: 2727,
					},
					{
						participantId: 3,
						totalGold: 14975,
						level: 18,
						kills: 5,
						deaths: 2,
						assists: 3,
						creepScore: 313,
						currentHealth: 661,
						maxHealth: 2923,
					},
					{
						participantId: 4,
						totalGold: 15214,
						level: 15,
						kills: 9,
						deaths: 2,
						assists: 3,
						creepScore: 288,
						currentHealth: 0,
						maxHealth: 2112,
					},
					{
						participantId: 5,
						totalGold: 7924,
						level: 14,
						kills: 1,
						deaths: 1,
						assists: 10,
						creepScore: 36,
						currentHealth: 891,
						maxHealth: 2331,
					},
				],
			},
			redTeam: {
				totalGold: 57062,
				inhibitors: 0,
				towers: 3,
				barons: 1,
				totalKills: 13,
				dragons: ['mountain'],
				participants: [
					{
						participantId: 6,
						totalGold: 10861,
						level: 16,
						kills: 2,
						deaths: 4,
						assists: 5,
						creepScore: 227,
						currentHealth: 2976,
						maxHealth: 2976,
					},
					{
						participantId: 7,
						totalGold: 9901,
						level: 14,
						kills: 0,
						deaths: 3,
						assists: 7,
						creepScore: 160,
						currentHealth: 3435,
						maxHealth: 3582,
					},
					{
						participantId: 8,
						totalGold: 13457,
						level: 16,
						kills: 3,
						deaths: 2,
						assists: 3,
						creepScore: 283,
						currentHealth: 2167,
						maxHealth: 2167,
					},
					{
						participantId: 9,
						totalGold: 13550,
						level: 15,
						kills: 5,
						deaths: 2,
						assists: 4,
						creepScore: 275,
						currentHealth: 586,
						maxHealth: 2084,
					},
					{
						participantId: 10,
						totalGold: 9293,
						level: 13,
						kills: 3,
						deaths: 4,
						assists: 3,
						creepScore: 37,
						currentHealth: 963,
						maxHealth: 1969,
					},
				],
			},
		},
		{
			rfc460Timestamp: '2023-11-11T12:09:48.805Z',
			gameState: 'in_game',
			blueTeam: {
				totalGold: 57775,
				inhibitors: 1,
				towers: 6,
				barons: 1,
				totalKills: 15,
				dragons: ['cloud', 'infernal', 'mountain', 'mountain'],
				participants: [
					{
						participantId: 1,
						totalGold: 9807,
						level: 15,
						kills: 0,
						deaths: 5,
						assists: 5,
						creepScore: 220,
						currentHealth: 0,
						maxHealth: 3981,
					},
					{
						participantId: 2,
						totalGold: 9855,
						level: 14,
						kills: 0,
						deaths: 3,
						assists: 9,
						creepScore: 155,
						currentHealth: 2727,
						maxHealth: 2727,
					},
					{
						participantId: 3,
						totalGold: 14975,
						level: 18,
						kills: 5,
						deaths: 2,
						assists: 3,
						creepScore: 313,
						currentHealth: 661,
						maxHealth: 2923,
					},
					{
						participantId: 4,
						totalGold: 15214,
						level: 15,
						kills: 9,
						deaths: 2,
						assists: 3,
						creepScore: 288,
						currentHealth: 0,
						maxHealth: 2112,
					},
					{
						participantId: 5,
						totalGold: 7924,
						level: 14,
						kills: 1,
						deaths: 1,
						assists: 10,
						creepScore: 36,
						currentHealth: 891,
						maxHealth: 2331,
					},
				],
			},
			redTeam: {
				totalGold: 57062,
				inhibitors: 0,
				towers: 3,
				barons: 1,
				totalKills: 13,
				dragons: ['mountain'],
				participants: [
					{
						participantId: 6,
						totalGold: 10861,
						level: 16,
						kills: 2,
						deaths: 4,
						assists: 5,
						creepScore: 227,
						currentHealth: 2976,
						maxHealth: 2976,
					},
					{
						participantId: 7,
						totalGold: 9901,
						level: 14,
						kills: 0,
						deaths: 3,
						assists: 7,
						creepScore: 160,
						currentHealth: 3435,
						maxHealth: 3582,
					},
					{
						participantId: 8,
						totalGold: 13457,
						level: 16,
						kills: 3,
						deaths: 2,
						assists: 3,
						creepScore: 283,
						currentHealth: 2167,
						maxHealth: 2167,
					},
					{
						participantId: 9,
						totalGold: 13550,
						level: 15,
						kills: 5,
						deaths: 2,
						assists: 4,
						creepScore: 275,
						currentHealth: 586,
						maxHealth: 2084,
					},
					{
						participantId: 10,
						totalGold: 9293,
						level: 13,
						kills: 3,
						deaths: 4,
						assists: 3,
						creepScore: 37,
						currentHealth: 963,
						maxHealth: 1969,
					},
				],
			},
		},
		{
			rfc460Timestamp: '2023-11-11T12:09:49.142Z',
			gameState: 'in_game',
			blueTeam: {
				totalGold: 57775,
				inhibitors: 1,
				towers: 6,
				barons: 1,
				totalKills: 15,
				dragons: ['cloud', 'infernal', 'mountain', 'mountain'],
				participants: [
					{
						participantId: 1,
						totalGold: 9807,
						level: 15,
						kills: 0,
						deaths: 5,
						assists: 5,
						creepScore: 220,
						currentHealth: 0,
						maxHealth: 3981,
					},
					{
						participantId: 2,
						totalGold: 9855,
						level: 14,
						kills: 0,
						deaths: 3,
						assists: 9,
						creepScore: 155,
						currentHealth: 2727,
						maxHealth: 2727,
					},
					{
						participantId: 3,
						totalGold: 14975,
						level: 18,
						kills: 5,
						deaths: 2,
						assists: 3,
						creepScore: 313,
						currentHealth: 661,
						maxHealth: 2923,
					},
					{
						participantId: 4,
						totalGold: 15214,
						level: 15,
						kills: 9,
						deaths: 2,
						assists: 3,
						creepScore: 288,
						currentHealth: 0,
						maxHealth: 2112,
					},
					{
						participantId: 5,
						totalGold: 7924,
						level: 14,
						kills: 1,
						deaths: 1,
						assists: 10,
						creepScore: 36,
						currentHealth: 891,
						maxHealth: 2331,
					},
				],
			},
			redTeam: {
				totalGold: 57062,
				inhibitors: 0,
				towers: 3,
				barons: 1,
				totalKills: 13,
				dragons: ['mountain'],
				participants: [
					{
						participantId: 6,
						totalGold: 10861,
						level: 16,
						kills: 2,
						deaths: 4,
						assists: 5,
						creepScore: 227,
						currentHealth: 2976,
						maxHealth: 2976,
					},
					{
						participantId: 7,
						totalGold: 9901,
						level: 14,
						kills: 0,
						deaths: 3,
						assists: 7,
						creepScore: 160,
						currentHealth: 3435,
						maxHealth: 3582,
					},
					{
						participantId: 8,
						totalGold: 13457,
						level: 16,
						kills: 3,
						deaths: 2,
						assists: 3,
						creepScore: 283,
						currentHealth: 2167,
						maxHealth: 2167,
					},
					{
						participantId: 9,
						totalGold: 13550,
						level: 15,
						kills: 5,
						deaths: 2,
						assists: 4,
						creepScore: 275,
						currentHealth: 586,
						maxHealth: 2084,
					},
					{
						participantId: 10,
						totalGold: 9293,
						level: 13,
						kills: 3,
						deaths: 4,
						assists: 3,
						creepScore: 37,
						currentHealth: 963,
						maxHealth: 1969,
					},
				],
			},
		},
		{
			rfc460Timestamp: '2023-11-11T12:09:49.207Z',
			gameState: 'in_game',
			blueTeam: {
				totalGold: 57786,
				inhibitors: 1,
				towers: 6,
				barons: 1,
				totalKills: 15,
				dragons: ['cloud', 'infernal', 'mountain', 'mountain'],
				participants: [
					{
						participantId: 1,
						totalGold: 9809,
						level: 15,
						kills: 0,
						deaths: 5,
						assists: 5,
						creepScore: 220,
						currentHealth: 0,
						maxHealth: 3981,
					},
					{
						participantId: 2,
						totalGold: 9858,
						level: 14,
						kills: 0,
						deaths: 3,
						assists: 9,
						creepScore: 155,
						currentHealth: 2727,
						maxHealth: 2727,
					},
					{
						participantId: 3,
						totalGold: 14977,
						level: 18,
						kills: 5,
						deaths: 2,
						assists: 3,
						creepScore: 313,
						currentHealth: 665,
						maxHealth: 2923,
					},
					{
						participantId: 4,
						totalGold: 15216,
						level: 15,
						kills: 9,
						deaths: 2,
						assists: 3,
						creepScore: 288,
						currentHealth: 0,
						maxHealth: 2112,
					},
					{
						participantId: 5,
						totalGold: 7926,
						level: 14,
						kills: 1,
						deaths: 1,
						assists: 10,
						creepScore: 36,
						currentHealth: 901,
						maxHealth: 2331,
					},
				],
			},
			redTeam: {
				totalGold: 57093,
				inhibitors: 0,
				towers: 3,
				barons: 1,
				totalKills: 13,
				dragons: ['mountain'],
				participants: [
					{
						participantId: 6,
						totalGold: 10863,
						level: 16,
						kills: 2,
						deaths: 4,
						assists: 5,
						creepScore: 227,
						currentHealth: 2976,
						maxHealth: 2976,
					},
					{
						participantId: 7,
						totalGold: 9903,
						level: 14,
						kills: 0,
						deaths: 3,
						assists: 7,
						creepScore: 160,
						currentHealth: 3443,
						maxHealth: 3585,
					},
					{
						participantId: 8,
						totalGold: 13459,
						level: 16,
						kills: 3,
						deaths: 2,
						assists: 3,
						creepScore: 283,
						currentHealth: 2167,
						maxHealth: 2167,
					},
					{
						participantId: 9,
						totalGold: 13573,
						level: 15,
						kills: 5,
						deaths: 2,
						assists: 4,
						creepScore: 276,
						currentHealth: 641,
						maxHealth: 2084,
					},
					{
						participantId: 10,
						totalGold: 9295,
						level: 13,
						kills: 3,
						deaths: 4,
						assists: 3,
						creepScore: 37,
						currentHealth: 985,
						maxHealth: 1969,
					},
				],
			},
		},
	],
};
