// https://esports-api.lolesports.com/persisted/gw/getLive?hl=en-US

export default {
	data: {
		schedule: {
			events: [
				{
					id: '110853020184706753',
					startTime: '2023-11-11T08:00:00Z',
					state: 'inProgress',
					type: 'match',
					blockName: 'Semifinals',
					league: {
						id: '98767975604431411',
						slug: 'worlds',
						name: 'Worlds',
						image: 'http://static.lolesports.com/leagues/1592594612171_WorldsDarkBG.png',
						priority: 300,
						displayPriority: {
							position: 0,
							status: 'force_selected',
						},
					},
					tournament: {
						id: '110852926142971547',
					},
					match: {
						id: '110853020184706753',
						teams: [
							{
								id: '99566404853058754',
								name: 'WeiboGaming FAW AUDI',
								slug: 'weibo-gaming',
								code: 'WBG',
								image: 'http://static.lolesports.com/teams/1641202879910_3.png',
								result: {
									outcome: null,
									gameWins: 2,
								},
								record: {
									wins: 1,
									losses: 0,
								},
							},
							{
								id: '99566404853854212',
								name: 'Bilibili Gaming Pingan Bank',
								slug: 'bilibili-gaming',
								code: 'BLG',
								image:
									'http://static.lolesports.com/teams/1682322954525_Bilibili_Gaming_logo_20211.png',
								result: {
									outcome: null,
									gameWins: 2,
								},
								record: {
									wins: 1,
									losses: 0,
								},
							},
						],
						strategy: {
							type: 'bestOf',
							count: 5,
						},
						games: [
							{
								number: 1,
								id: '110853020184706754',
								state: 'completed',
								teams: [
									{
										id: '99566404853058754',
										side: 'blue',
									},
									{
										id: '99566404853854212',
										side: 'red',
									},
								],
								vods: [
									{
										id: '111391187080928948',
										parameter: '9MTWN4ZeiFg',
										locale: 'en-US',
										mediaLocale: {
											locale: 'en-US',
											englishName: 'English (North America)',
											translatedName: 'English (North America)',
										},
										provider: 'youtube',
										offset: 0,
										firstFrameTime: '2023-11-11T07:29:57Z',
										startMillis: null,
										endMillis: null,
									},
									{
										id: '111391126950831936',
										parameter: 'K4al8fKgjQc',
										locale: 'es-MX',
										mediaLocale: {
											locale: 'es-MX',
											englishName: 'Spanish (Mexico)',
											translatedName: 'Español (Latinoamérica)',
										},
										provider: 'youtube',
										offset: 0,
										firstFrameTime: '2023-11-11T08:10:25Z',
										startMillis: 420000,
										endMillis: 2158000,
									},
								],
							},
							{
								number: 2,
								id: '110853020184706755',
								state: 'completed',
								teams: [
									{
										id: '99566404853854212',
										side: 'blue',
									},
									{
										id: '99566404853058754',
										side: 'red',
									},
								],
								vods: [
									{
										id: '111391351281704654',
										parameter: 'nuTvUBJXrZs',
										locale: 'en-US',
										mediaLocale: {
											locale: 'en-US',
											englishName: 'English (North America)',
											translatedName: 'English (North America)',
										},
										provider: 'youtube',
										offset: 0,
										firstFrameTime: '2023-11-11T09:00:10Z',
										startMillis: null,
										endMillis: null,
									},
									{
										id: '111391347248887780',
										parameter: 'pBwVUxdAfMs',
										locale: 'es-MX',
										mediaLocale: {
											locale: 'es-MX',
											englishName: 'Spanish (Mexico)',
											translatedName: 'Español (Latinoamérica)',
										},
										provider: 'youtube',
										offset: 0,
										firstFrameTime: '2023-11-11T08:59:45Z',
										startMillis: 439000,
										endMillis: 2541000,
									},
								],
							},
							{
								number: 3,
								id: '110853020184706756',
								state: 'completed',
								teams: [
									{
										id: '99566404853058754',
										side: 'blue',
									},
									{
										id: '99566404853854212',
										side: 'red',
									},
								],
								vods: [
									{
										id: '111391547610490781',
										parameter: 'ZpU8Oks4bNQ',
										locale: 'en-US',
										mediaLocale: {
											locale: 'en-US',
											englishName: 'English (North America)',
											translatedName: 'English (North America)',
										},
										provider: 'youtube',
										offset: 0,
										firstFrameTime: '2023-11-11T09:55:11Z',
										startMillis: null,
										endMillis: null,
									},
									{
										id: '111391513585117079',
										parameter: 'm30S3evwelw',
										locale: 'es-MX',
										mediaLocale: {
											locale: 'es-MX',
											englishName: 'Spanish (Mexico)',
											translatedName: 'Español (Latinoamérica)',
										},
										provider: 'youtube',
										offset: 0,
										firstFrameTime: '2023-11-11T09:55:27Z',
										startMillis: 412000,
										endMillis: 2075000,
									},
								],
							},
							{
								number: 4,
								id: '110853020184706757',
								state: 'completed',
								teams: [
									{
										id: '99566404853854212',
										side: 'blue',
									},
									{
										id: '99566404853058754',
										side: 'red',
									},
								],
								vods: [
									{
										id: '111391711254509600',
										parameter: '3rZ2E__IovA',
										locale: 'en-US',
										mediaLocale: {
											locale: 'en-US',
											englishName: 'English (North America)',
											translatedName: 'English (North America)',
										},
										provider: 'youtube',
										offset: 0,
										firstFrameTime: '2023-11-11T10:35:46Z',
										startMillis: null,
										endMillis: null,
									},
									{
										id: '111391717828353814',
										parameter: 'bkqZrKVAuek',
										locale: 'es-MX',
										mediaLocale: {
											locale: 'es-MX',
											englishName: 'Spanish (Mexico)',
											translatedName: 'Español (Latinoamérica)',
										},
										provider: 'youtube',
										offset: 0,
										firstFrameTime: '2023-11-11T10:43:31Z',
										startMillis: 426000,
										endMillis: 2109000,
									},
								],
							},
							{
								number: 5,
								id: '110853020184706758',
								state: 'inProgress',
								teams: [
									{
										id: '99566404853058754',
										side: 'blue',
									},
									{
										id: '99566404853854212',
										side: 'red',
									},
								],
								vods: [],
							},
						],
					},
					streams: [
						{
							parameter: 'summonersinnlive',
							locale: 'de-DE',
							mediaLocale: {
								locale: 'de-DE',
								englishName: 'German (Germany)',
								translatedName: 'Deutsch',
							},
							provider: 'twitch',
							countries: ['DE', 'AT', 'CH'],
							offset: -60000,
							statsStatus: 'enabled',
						},
						{
							parameter: 'esport2tv',
							locale: 'hu-HU',
							mediaLocale: {
								locale: 'hu-HU',
								englishName: 'Hungarian (Hungary)',
								translatedName: 'Magyar',
							},
							provider: 'twitch',
							countries: [],
							offset: -60000,
							statsStatus: 'enabled',
						},
						{
							parameter: 'riotgames',
							locale: 'en-US',
							mediaLocale: {
								locale: 'en-US',
								englishName: 'English (North America)',
								translatedName: 'English (North America)',
							},
							provider: 'twitch',
							countries: [],
							offset: -60000,
							statsStatus: 'enabled',
						},
						{
							parameter: 'tYNLtcnJEFU',
							locale: 'en-US',
							mediaLocale: {
								locale: 'en-US',
								englishName: 'English (North America)',
								translatedName: 'English (North America)',
							},
							provider: 'youtube',
							countries: [],
							offset: -60000,
							statsStatus: 'enabled',
						},
						{
							parameter: 'lolpacificTW',
							locale: 'zh-TW',
							mediaLocale: {
								locale: 'zh-TW',
								englishName: 'Chinese (Republic of China)',
								translatedName: '繁體中文',
							},
							provider: 'twitch',
							countries: [],
							offset: -60000,
							statsStatus: 'enabled',
						},
						{
							parameter: 'lolpacifichk',
							locale: 'zh-HK',
							mediaLocale: {
								locale: 'zh-HK',
								englishName: 'Chinese (Hong Kong)',
								translatedName: '繁體中文 (香港)',
							},
							provider: 'twitch',
							countries: [],
							offset: -60000,
							statsStatus: 'enabled',
						},
						{
							parameter: 'cblol',
							locale: 'pt-BR',
							mediaLocale: {
								locale: 'pt-BR',
								englishName: 'Portuguese (Brazil)',
								translatedName: 'Português (Brasil)',
							},
							provider: 'twitch',
							countries: ['BR'],
							offset: -60000,
							statsStatus: 'enabled',
						},
						{
							parameter: 'Q6LJgvOyjSI',
							locale: 'pt-BR',
							mediaLocale: {
								locale: 'pt-BR',
								englishName: 'Portuguese (Brazil)',
								translatedName: 'Português (Brasil)',
							},
							provider: 'youtube',
							countries: [],
							offset: -60000,
							statsStatus: 'enabled',
						},
						{
							parameter: 'aflol',
							locale: 'ko-KR',
							mediaLocale: {
								locale: 'ko-KR',
								englishName: 'Korean (Korea)',
								translatedName: '한국어',
							},
							provider: 'afreecatv',
							countries: [],
							offset: -60000,
							statsStatus: 'enabled',
						},
						{
							parameter: 'lvpes',
							locale: 'es-ES',
							mediaLocale: {
								locale: 'es-ES',
								englishName: 'Spanish (Spain)',
								translatedName: 'Español (España)',
							},
							provider: 'twitch',
							countries: [],
							offset: -60000,
							statsStatus: 'enabled',
						},
						{
							parameter: 'lolesports_ar',
							locale: 'ar-AE',
							mediaLocale: {
								locale: 'ar-AE',
								englishName: 'Arabic',
								translatedName: 'اَلْعَرَبِيَّةُ',
							},
							provider: 'twitch',
							countries: [],
							offset: 0,
							statsStatus: 'disabled',
						},
						{
							parameter: 'lla',
							locale: 'es-MX',
							mediaLocale: {
								locale: 'es-MX',
								englishName: 'Spanish (Mexico)',
								translatedName: 'Español (Latinoamérica)',
							},
							provider: 'twitch',
							countries: [],
							offset: -60000,
							statsStatus: 'enabled',
						},
						{
							parameter: 'ggsMPfDEVOw',
							locale: 'es-MX',
							mediaLocale: {
								locale: 'es-MX',
								englishName: 'Spanish (Mexico)',
								translatedName: 'Español (Latinoamérica)',
							},
							provider: 'youtube',
							countries: [],
							offset: -60000,
							statsStatus: 'enabled',
						},
						{
							parameter: 'pg_esports_lol',
							locale: 'it-IT',
							mediaLocale: {
								locale: 'it-IT',
								englishName: 'Italian (Italy)',
								translatedName: 'Italiano',
							},
							provider: 'twitch',
							countries: [],
							offset: -60000,
							statsStatus: 'enabled',
						},
						{
							parameter: 'gamersloungegr',
							locale: 'el-GR',
							mediaLocale: {
								locale: 'el-GR',
								englishName: 'Greek (Greece)',
								translatedName: 'Ελληνικά',
							},
							provider: 'twitch',
							countries: [],
							offset: -60000,
							statsStatus: 'enabled',
						},
						{
							parameter: 'polsatgames',
							locale: 'pl-PL',
							mediaLocale: {
								locale: 'pl-PL',
								englishName: 'Polish (Poland)',
								translatedName: 'Polski',
							},
							provider: 'twitch',
							countries: ['PL'],
							offset: -60000,
							statsStatus: 'enabled',
						},
						{
							parameter: 'riotgamesturkish',
							locale: 'tr-TR',
							mediaLocale: {
								locale: 'tr-TR',
								englishName: 'Turkish (Turkey)',
								translatedName: 'Türkçe',
							},
							provider: 'twitch',
							countries: [],
							offset: -60000,
							statsStatus: 'enabled',
						},
						{
							parameter: 'hitpointcz',
							locale: 'cs-CZ',
							mediaLocale: {
								locale: 'cs-CZ',
								englishName: 'Czech (Czechia)',
								translatedName: 'Čeština',
							},
							provider: 'twitch',
							countries: [],
							offset: -60000,
							statsStatus: 'enabled',
						},
						{
							parameter: 'otplol_',
							locale: 'fr-FR',
							mediaLocale: {
								locale: 'fr-FR',
								englishName: 'French (France)',
								translatedName: 'Français',
							},
							provider: 'twitch',
							countries: ['FR', 'CA'],
							offset: -60000,
							statsStatus: 'enabled',
						},
						{
							parameter: 'l4ME55lz2jg',
							locale: 'vi-VN',
							mediaLocale: {
								locale: 'vi-VN',
								englishName: 'Vietnamese (Vietnam)',
								translatedName: 'Tiếng Việt',
							},
							provider: 'youtube',
							countries: [],
							offset: -60000,
							statsStatus: 'enabled',
						},
						{
							parameter: 'riotgamesjp',
							locale: 'ja-JP',
							mediaLocale: {
								locale: 'ja-JP',
								englishName: 'Japanese (Japan)',
								translatedName: '日本語',
							},
							provider: 'twitch',
							countries: [],
							offset: -60000,
							statsStatus: 'enabled',
						},
						{
							parameter: 'ljl',
							locale: 'ja-JP',
							mediaLocale: {
								locale: 'ja-JP',
								englishName: 'Japanese (Japan)',
								translatedName: '日本語',
							},
							provider: 'afreecatv',
							countries: [],
							offset: -60000,
							statsStatus: 'enabled',
						},
					],
				},
			],
		},
	},
};
